name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - nr/feat/next-js
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - nr/feat/next-js

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '22'
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v7.0.1
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js app
        run: npm run next:build
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_PEBBLE_0E111C403 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          REACT_APP_UMBRACO_API_KEY: ${{ secrets.REACT_APP_UMBRACO_API_KEY }}
          NEXT_PUBLIC_UMBRACO_API_KEY: ${{ secrets.REACT_APP_UMBRACO_API_KEY }}
          CMS_ENDPOINT: ${{ secrets.CMS_ENDPOINT }}
          REACT_APP_UMBRACO_MANAGEMENT_ENDPOINT: ${{ secrets.REACT_APP_UMBRACO_MANAGEMENT_ENDPOINT }}
          NEXT_PUBLIC_UMBRACO_API_URL: ${{ secrets.NEXT_PUBLIC_UMBRACO_API_URL }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
